In [1]:
import numpy as np

## NumPy Arrays

In [2]:
# All Items Of NumpyArray are of same data type
att_str = ["Mercedes", "BMW", "Audi", "Ferrari", "Tesla"]
arr_num = [5, 4, 7, 3]

In [3]:
# Converting list to NumpyArray
np_array_str = np.array(att_str)
np_array_num = np.array(arr_num)

print(f"Numpy Array (arr_str): {np_array_str} : of {type(np_array_str)}")
print(f"Numpy Array (arr_num): {np_array_num} : of {type(np_array_num)}")

Numpy Array (arr_str): ['Mercedes' 'BMW' 'Audi' 'Ferrari' 'Tesla'] : of <class 'numpy.ndarray'>
Numpy Array (arr_num): [5 4 7 3] : of <class 'numpy.ndarray'>


In [ ]:
# Numpy Matrix
matrix = np.array([[1,2,1], [4,5,9], [1,8,9]])
print(f"Matix {matrix} Is of type: {type(matrix)}")

Matix [[1 2 1]
 [4 5 9]
 [1 8 9]] Is of type: <class 'numpy.ndarray'>


## Numpy Functions

**arange function**

In [ ]:
# arange Function
arr_step_2 = np.arange(start= 0,
                 stop= 10,
                 step= 2)
arr_step_5 = np.arange(start= 0,
                 stop= 20,
                 step= 5)
arr_step_default = np.arange(start= 0, # Default Step Size = 1
                 stop= 10)
print(f"arr_step_2: {arr_step_2}")
print(f"arr_step_5: {arr_step_5}")
print(f"arr_step_default: {arr_step_default}")

arr_step_2: [0 2 4 6 8]
arr_step_5: [ 0  5 10 15]
arr_step_default: [0 1 2 3 4 5 6 7 8 9]


**linspace function**

In [ ]:
# linspace Function
matrix_20 = np.linspace(start= 0,
                       stop= 100,
                       num = 20) # Deafult value 50
print(f"20 Equally Distributed samples between 0 and 100: {matrix_20}")
print(f"Sample Step Size: {(100 - 0) / 19}") # (stop - start) / num_of_samples - 1

20 Equally Distributed samples between 0 and 100: [  0.           5.26315789  10.52631579  15.78947368  21.05263158
  26.31578947  31.57894737  36.84210526  42.10526316  47.36842105
  52.63157895  57.89473684  63.15789474  68.42105263  73.68421053
  78.94736842  84.21052632  89.47368421  94.73684211 100.        ]
Sample Step Size: 5.2631578947368425


**zeros and ones function**

In [ ]:
# Zeros and Ones Function
matrix_zero = np.zeros(shape= [3,5]) # Default dType float
matrix_zero_int = np.zeros(shape= [3,5],
                           dtype= int)
matrix_one = np.ones(shape= [3,5])  # Default dType float
matrix_one_int = np.ones(shape= [3,5],
                           dtype= int)
print("3 rows and 5 coluns filled with Zeros:", matrix_zero)
print("3 rows and 5 coluns filled with Zeros:", matrix_zero_int)
print("3 rows and 5 coluns filled with Ones:", matrix_one)
print("3 rows and 5 coluns filled with Ones:", matrix_one_int)

3 rows and 5 coluns filled with Zeros: [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
3 rows and 5 coluns filled with Zeros: [[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
3 rows and 5 coluns filled with Ones: [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
3 rows and 5 coluns filled with Ones: [[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


**eye function**

In [ ]:
# Eye Function For Identity Matrix
# - matrix is squre with all zeros with diagonals ones
matrix_identity = np.eye(N= 5,
                         dtype=int)
print(f"Identity Matrix [5x5]: {matrix_identity}")

Identity Matrix [5x5]: [[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


**reshape method**

In [ ]:
# Reshape Function
array_1 = np.arange(0,10)
reshaped_array_1 = array_1.reshape([2,5])
print(f"Reshaped Array: {reshaped_array_1}")

Reshaed Array: [[0 1 2 3 4]
 [5 6 7 8 9]]


**Trignomtric Functions**

In [ ]:
print(f"Sine Function: {np.sin(4)}")
print(f"Cosine Function: {np.cos(4)}")
print(f"Tan Function: {np.tan(4)}")

Sine Function: -0.7568024953079282
Cosine Function: -0.6536436208636119
Tan Function: 1.1578212823495775


**Exponent & Logarithmic Function**

In [ ]:
print(f"Exponent Num: {np.exp(2)}")
print(f"Exponent NumpyArray: {np.exp(np.arange(2,6,2))}")

Exponent Num: 7.38905609893065
Exponent NumpyArray: [ 7.3890561  54.59815003]


In [ ]:
print(f"Log_e Num: {np.log(2)}")
print(f"Log_10 Num: {np.log10(100)}")
print(f"Log_2 Num: {np.log2(8)}")
print(f"Log_e NumpyArray: {np.log(np.arange(2,6,2))}")
print(f"Log_10 NumpyArray: {np.log10(np.arange(2,6,2))}")

Log_e Num: 0.6931471805599453
Log_10 Num: 2.0
Log_2 Num: 3.0
Log_e NumpyArray: [0.69314718 1.38629436]
Log_10 NumpyArray: [0.30103    0.60205999]


**Arithmetic Operation**

In [ ]:
p_array1 = [1,2,3]
p_array2 = [4,5,6]
print(f"Python Array Sum: {p_array1 + p_array2}")

np_array_1 = np.array(p_array1)
np_array_2 = np.array(p_array2)
print(f"NumPy Array Sum: {np_array_1 + np_array_2}")
print(f"NumPy Array Sub: {np_array_1 - np_array_2}")
print(f"NumPy Array Mul: {np_array_1 * np_array_2}")
print(f"NumPy Array Dev: {np_array_1 / np_array_2}")
print(f"NumPy Array Powers: {np_array_1 ** np_array_2}")

Python Array Sum: [1, 2, 3, 4, 5, 6]
NumPy Array Sum: [5 7 9]
NumPy Array Sub: [-3 -3 -3]
NumPy Array Mul: [ 4 10 18]
NumPy Array Dev: [0.25 0.4  0.5 ]
NumPy Array Powers: [  1  32 729]


In [ ]:
# Operation on Matrix
matrix_1 = np.arange(start=1, stop=10).reshape(3,3)
matrix_2 = np.eye(3, dtype=int)
matrix_3 = np.ones(shape= (3,3), dtype=int)

print(matrix_1)
print(matrix_2)
print(matrix_3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 0 0]
 [0 1 0]
 [0 0 1]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [ ]:
print(f"Matrix Addtion: \n {matrix_1 + matrix_2}")
print(f"Matrix Sub: \n {matrix_1 - matrix_2}")
print(f"Matrix mul: \n {matrix_1 * matrix_2}")
print(f"Matrix div: \n {matrix_1 / matrix_3}")
print(f"Matrix Linear mul: \n {matrix_1 @ matrix_3}")

Matrix Addtion: 
 [[ 2  2  3]
 [ 4  6  6]
 [ 7  8 10]]
Matrix Sub: 
 [[0 2 3]
 [4 4 6]
 [7 8 8]]
Matrix mul: 
 [[1 0 0]
 [0 5 0]
 [0 0 9]]
Matrix div: 
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
Matrix Linear mul: 
 [[ 6  6  6]
 [15 15 15]
 [24 24 24]]


In [ ]:
# Transpose of matrix
matrix_for_trans = np.arange(1, 11).reshape([2,5])
matrix_trans = np.transpose(matrix_for_trans)
print(f"Original Matrix: \n{matrix_for_trans}")
print(f"Transpose Matrix: \n{matrix_for_trans.T}")
print(f"Transpose Matrix: \n{matrix_trans}")

Original Matrix: 
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Transpose Matrix: 
[[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]
Transpose Matrix: 
[[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]


**Min Max Functions**

In [ ]:
vec = np.arange(1,10).reshape([3,3])
print("Max value:", np.max(vec))
print("Min value:", np.min(vec))

Max value: 9
Min value: 1


**Random Function**

In [ ]:
rand_mat = np.random.rand(5)
rand_mat_uniform = np.random.rand(5,5)
rand_mat_n = np.random.randn(5,5)
rand_int = np.random.randint(0, 5, 10)
rand_mat_int = np.random.randint(0, 10, [5,5])
print("Random Matrix [1x5]: ", rand_mat)
print("Random Matrix Int [5x5]: ", rand_mat_n)
print("Random Matrix [5x5]: ", rand_mat_uniform)
print("Random Int [1x5]: ", rand_int)
print("Random Int [2x2]: ", rand_mat_int)

Random Matrix [1x5]:  [0.98892629 0.07558018 0.33660984 0.40574336 0.9058255 ]
Random Matrix Int [5x5]:  [[-1.21521559e+00  3.84760134e-01 -5.95195183e-01 -4.90935182e-01
  -1.33292949e-01]
 [-7.04832393e-01  1.45702983e+00  1.16057871e+00 -2.36607785e-01
   1.09696114e+00]
 [-1.19189546e-01 -6.28356456e-02 -1.47167864e+00  1.92541482e+00
  -1.53622002e+00]
 [ 7.53167181e-04 -4.80233620e-02  1.74650772e+00  5.42203779e-02
   1.05184241e-01]
 [ 1.02199089e+00  2.09403467e-01 -1.57441651e+00  7.10146652e-01
  -7.79893600e-02]]
Random Matrix [5x5]:  [[0.72993138 0.19352958 0.82542667 0.72378971 0.27868969]
 [0.38198462 0.15306765 0.24544063 0.27355242 0.07211084]
 [0.13884148 0.18950806 0.28388621 0.24677198 0.67082527]
 [0.13080547 0.78093121 0.71551199 0.60480099 0.71478502]
 [0.18188167 0.26918959 0.50575971 0.27795234 0.75783036]]
Random Int [1x5]:  [1 2 1 3 1 2 2 4 0 0]
Random Int [2x2]:  [[3 5 6 5 0]
 [1 2 0 6 1]
 [3 6 8 6 9]
 [5 0 4 1 1]
 [2 5 9 4 0]]


**Mean & Median**

In [ ]:
print("Mean: ",np.mean(rand_mat_n) )
print("Std: ",np.std(rand_mat_n) )

Mean:  -0.2416120181438781
Std:  0.9212822313869832


## Accessing Numpy Array

In [ ]:
# Accessing Array
rand_arry = np.random.rand(10)
print(f"rand_array: {rand_arry}")
print(f"rand_array[0:4]: {rand_arry[0:4]}")
print(f"rand_array[rand_arry[np.arange(3,10,3]: {rand_arry[np.arange(3,10,3)]}")
print(f"rand_array[rand_arry>0]: {rand_arry[rand_arry > 0]}")
print(f"rand_array[rand_arry>0]: {rand_arry[rand_arry < 0]}")

rand_array: [0.58885204 0.09485763 0.03821619 0.13695764 0.48384585 0.27930765
 0.50171482 0.2925983  0.1967723  0.75369869]
rand_array[0:4]: [0.58885204 0.09485763 0.03821619 0.13695764]
rand_array[rand_arry[np.arange(3,10,3]: [0.13695764 0.50171482 0.75369869]
rand_array[rand_arry>0]: [0.58885204 0.09485763 0.03821619 0.13695764 0.48384585 0.27930765
 0.50171482 0.2925983  0.1967723  0.75369869]
rand_array[rand_arry>0]: []


In [ ]:
# Accessing Matrix
rand_m = np.random.randn(5, 5)
print("Matrix 5x5: \n", rand_m)
print("Matrix[1,4] - 1st row and 4ith column: \n", rand_m[1,4])
print("Matrix[2] - 2nd row: \n", rand_m[2])
print("Matrix[0:2, 1:3] - 0 and 2nd row with 1 and 3 column: \n", rand_m[0:2, 1:3])

Matrix 5x5: 
 [[ 0.21022358 -1.63644243 -0.17192432  0.68226453 -0.23983353]
 [ 0.09660645  1.03856786 -1.75233759 -0.68710158  0.54077792]
 [-0.75561182 -0.35148619  1.64085521  1.73929987 -1.29444116]
 [-0.0239651  -1.18546159 -0.7410116  -0.73999392  0.54546994]
 [ 0.8925556  -1.22947548 -2.4851234   0.27420982 -1.26127215]]
Matrix[1,4] - 1st row and 4ith column: 
 0.5407779190057778
Matrix[2] - 2nd row: 
 [-0.75561182 -0.35148619  1.64085521  1.73929987 -1.29444116]
Matrix[2] - 2nd row: 
 [[-1.63644243 -0.17192432]
 [ 1.03856786 -1.75233759]]


## Modifying NumPy Array

In [ ]:
print(rand_arry)
# Change values of index 3 and 4 to 5
rand_arry[3:5] = 5
print("Values of index 3 and 4 to 5",rand_arry)
# Change value of index 0 and 1 to 2 and 3
rand_arry[0:2] = [2,3]
print("Values of index 0 and 1 to 2,3: ",rand_arry[0],rand_arry[1])

[2.         3.         0.03821619 5.         5.         0.27930765
 0.50171482 0.2925983  0.1967723  0.75369869]
Values of index 3 and 4 to 5 [2.         3.         0.03821619 5.         5.         0.27930765
 0.50171482 0.2925983  0.1967723  0.75369869]
Values of index 0 and 1 to 2,3:  2.0 3.0


## Modifying NumPy Matrix

In [ ]:
rand_mat_3 = np.random.randint(1, 10, [5,5])
print("Before 5x5 Matrix: \n", rand_mat_3)
rand_mat_3[1:3, 3:5] = 0
print("After 5x5 Matrix: \n", rand_mat_3)
# Extracting first 2 rows and first 3 column
sub_matrix = rand_mat_3[0:2, 0:3].copy()
print("Sub-Matrix: \n", sub_matrix)
sub_matrix[:] = 3
print("Sub-Matrix Updated: \n", sub_matrix)

Before 5x5 Matrix: 
 [[7 2 4 7 7]
 [9 5 5 8 1]
 [5 4 3 2 1]
 [3 4 4 5 8]
 [5 3 3 5 8]]
After 5x5 Matrix: 
 [[7 2 4 7 7]
 [9 5 5 0 0]
 [5 4 3 0 0]
 [3 4 4 5 8]
 [5 3 3 5 8]]
Sub-Matrix: 
 [[7 2 4]
 [9 5 5]]
Sub-Matrix Updated: 
 [[3 3 3]
 [3 3 3]]


## Saving and Loading NumPy Array

In [9]:
from google.colab import drive

drive.mount("/content/drive")

Mounted at /content/drive


### Saving

In [22]:
# Create random matrices
randint_matrix1 = np.random.randint(1,10,10).reshape(2,5)
randint_matrix2 = np.random.randint(1,20,10).reshape(2,5)
print(randint_matrix1)
print(randint_matrix2)

[[4 8 5 4 9]
 [2 1 3 2 2]]
[[16 10  8  1  7]
 [13 17  2  6 17]]


In [23]:
np.save("/content/drive/My Drive/DataAnalytics/saved_file_name", randint_matrix1)

In [24]:
np.savez("/content/drive/My Drive/DataAnalytics/multiple_saved_file_name", randint_matrix1, randint_matrix2)

### Loading

In [26]:
loaded_matrix = np.load("/content/drive/My Drive/DataAnalytics/saved_file_name.npy")
print(loaded_matrix)

[[9 4 2 2 2]
 [1 7 8 5 5]]


In [28]:
loaded_combined_matrix = np.load("/content/drive/My Drive/DataAnalytics/multiple_saved_file_name.npz")
print(loaded_combined_matrix)

print(loaded_combined_matrix["arr_0"])
print(loaded_combined_matrix["arr_1"])

NpzFile '/content/drive/My Drive/DataAnalytics/multiple_saved_file_name.npz' with keys: arr_0, arr_1
[[4 8 5 4 9]
 [2 1 3 2 2]]
[[16 10  8  1  7]
 [13 17  2  6 17]]


In [4]:
np.array([[9,8,7], [6,5,4], [3,2,1]])

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [13]:
np.cos([0,1,2,3,4])

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [8]:
np.matrix([[1,4,9,121,144,169],
           [16,25,36,196,225,256],
           [49,64,81,289,324,361]]).mean()

np.float64(131.66666666666666)

In [24]:
a = np.array([1,2,3,5,8])
b = np.array([0,3,4,2,1])
c = a + b
d = c * a
d[2]

np.int64(21)

In [27]:
np.ones([2,2])

array([[1., 1.],
       [1., 1.]])

In [29]:
n1 = np.matrix([[121,144,169],
           [196,225,256],
           [289,324,361]])
n2 = np.matrix([[1,4,9],
                [1,5,4],
                [9,4,8]])
n1@n2

matrix([[1786, 1880, 3017],
        [2725, 2933, 4712],
        [3862, 4220, 6785]])